### ISSUE TITLE
add template info to readme

### ISSUE THREAD

**Issue by kcranston** [CanDIG/repository-template#1]
Format the readme with the headings that we expect to see in a new candig repo, wtih some descriptive text about what goes in each section.

**Comment by mshadbolt** [comment]
used an existing template from '[scottydocs](https://github.com/scottydocs/README-template.md/tree/master)' seemed to be pretty decent. Are there any badges we consistently use across all the repos that would be worth adding at the top of the template? (may also bring this up in slack if nothing springs to mind)
