### ISSUE TITLE
add code of conduct

### ISSUE THREAD

**Issue by kcranston** [CanDIG/repository-template#4]
Add the candig code of conduct (once it exists and is approved).

**Comment by rauthanshubham1** [comment]
hello , i want to make code of conduct ,plz assign this to me

**Comment by kcranston** [comment]
Sorry, @rauthanshubham1 this needs to happen and be approved internally

**Comment by mshadbolt** [comment]
I used an existing template from GitHub ([contributor covenant](https://www.contributor-covenant.org/)), do you think this would be sufficient @kcranston or should we look into designing our own specific CanDIG Code of Conduct?

**Comment by mshadbolt** [comment]
resolved in meeting with @kcranston agreeing it is okay to use the github recommended code of conduct
